when:
  - event: tag
    # branch: main

steps:
  - name: build
    image: fedora:40
    commands:
      - echo "Install openjdk-devel"
      - dnf install -y java-21-openjdk-devel
      - dnf install -y java-21-openjdk-jmods
      - dnf install -y fakeroot
      - dnf install -y git
      - dnf install -y rpm-build
      - ./gradlew clean build
      - |
        jpackage \
          --name "adventure" \
          --dest output \
          --input build/libs/ \
          --main-jar adventure.jar  \
          --app-version 0.8 \
          --add-modules java.rmi \
          --linux-shortcut \
          --resource-dir resources

  - name: release-rpm
    image: plugins/gitea-release
    settings:
      base_url: https://codeberg.org
      api_key:
        from_secret: codeberg_token
      files:
        - output/*.rpm

