
steps:
  - name: publish-release
    image: codeberg.org/woodpecker-plugins/release
    settings:
      base_url: https://codeberg.org
      api_key:
        from_secret: woodpecker-release-token 
      files:
        - "output/*.deb"
        - "output/*.rpm"
      note: Changelog.md
      title: "${CI_COMMIT_TAG}"
    when:
      ref: refs/tags/*
