
name: Build and release rpm

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse Version Tag
        id: versioning
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG#v}
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Install JDK 21
        run: |
          dnf install -y java-21-openjdk-devel
          dnf install -y java-21-openjdk-jmods
          dnf install -y rpm-build

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build JAR with Gradle
        run: ./gradlew clean build

      - name: Package RPM with jpackage
        run: |
          jpackage \
            --type rpm \
            --dest output/ \
            --name adventure \
            --input build/libs/ \
            --main-jar adventure.jar \
            --linux-shortcut \
            --resource-dir resources/

      - name: Create Github release and Upload RPM
        uses: softprops/action-gh-release@v2
        with: 
          files: output/*.rpm

