name: Build Linux application image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: make linux package folder
        shell: bash
        run: mkdir linux

      - name: Build the application
        run: ./gradlew clean build

      - name: Create Linux app image
        shell: bash
        run: |
          set -euo pipefail
          jpackage \
            --name "adventure" \
            --input build/libs/ \
            --main-jar adventure.jar  \
            --app-version 0.8 \
            --linux-shortcut \
            --resource-dir resources





