name: Build Linux application image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest

    permissions:
      contents: write # can write to repo

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build the application
        run: ./gradlew clean build

      - name: Create Linux app image
        shell: bash
        run: |
          set -euo pipefail
          jpackage \
            --name "adventure" \
            --dest linux \
            --input build/libs/ \
            --main-jar adventure.jar  \
            --app-version 0.8 \
            --linux-shortcut \
            --resource-dir resources

      - name: Commit and push .deb to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add linux/
          git commit -m "build: add generated package [skip ci]" || echo "No changes to commit"
          git push





